<?php if ( ! defined('IN_DILICMS')) exit('No direct script access allowed');
$setting['cate_models']['news']=array (
  'id' => '1',
  'name' => 'news',
  'description' => '新闻中心',
  'perpage' => '20',
  'level' => '3',
  'hasattach' => '1',
  'built_in' => '0',
  'auto_update' => '1',
  'thumb_preferences' => '{"enabled":["40x40"],"default":"original"}',
  'fields' => 
  array (
    1 => 
    array (
      'id' => '1',
      'name' => 'n_id',
      'description' => '主键',
      'model' => '1',
      'type' => 'int',
      'length' => '11',
      'values' => '',
      'width' => '0',
      'height' => '0',
      'rules' => 'required',
      'ruledescription' => '自增长字段',
      'searchable' => '0',
      'listable' => '1',
      'order' => '1',
      'editable' => '1',
    ),
    2 => 
    array (
      'id' => '2',
      'name' => 'n_title',
      'description' => '新闻标题',
      'model' => '1',
      'type' => 'input',
      'length' => '0',
      'values' => '',
      'width' => '150',
      'height' => '20',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '1',
      'listable' => '1',
      'order' => '2',
      'editable' => '1',
    ),
    4 => 
    array (
      'id' => '4',
      'name' => 'n_create_at',
      'description' => '创建时间',
      'model' => '1',
      'type' => 'datetime',
      'length' => '0',
      'values' => '',
      'width' => '150',
      'height' => '20',
      'rules' => '',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '3',
      'editable' => '0',
    ),
    5 => 
    array (
      'id' => '5',
      'name' => 'n_del',
      'description' => '是否启用',
      'model' => '1',
      'type' => 'radio',
      'length' => '3',
      'values' => 
      array (
        0 => '启用',
        1 => '禁用',
      ),
      'width' => '30',
      'height' => '30',
      'rules' => 'required',
      'ruledescription' => '0表示不删除, 1表示删除',
      'searchable' => '0',
      'listable' => '1',
      'order' => '4',
      'editable' => '1',
    ),
    3 => 
    array (
      'id' => '3',
      'name' => 'n_content',
      'description' => '新闻内容',
      'model' => '1',
      'type' => 'wysiwyg',
      'length' => '0',
      'values' => '',
      'width' => '600',
      'height' => '300',
      'rules' => 'required',
      'ruledescription' => '',
      'searchable' => '0',
      'listable' => '1',
      'order' => '5',
      'editable' => '1',
    ),
  ),
  'listable' => 
  array (
    0 => '1',
    1 => '2',
    2 => '4',
    3 => '5',
    4 => '3',
  ),
  'searchable' => 
  array (
    0 => '2',
  ),
);